trigger:
- master

pr:
- master

stages:

- stage: build

  variables:
    nodeVersion: 13.x
    appDir: ticket-master

  jobs:

  - job: build

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: node $(nodeVersion)

    - script: npm ci
      workingDirectory: $(appDir)
      displayName: npm install

    - script: npx ng build --outputPath $(Build.ArtifactStagingDirectory)/app --prod
      workingDirectory: $(appDir)
      displayName: ng build

    - publish: $(Build.ArtifactStagingDirectory)/app
      artifact: app
      displayName: artifact publish app

  - job: test

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)
      displayName: node $(nodeVersion)

    - script: npm ci
      workingDirectory: $(appDir)
      displayName: npm install

- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: build

  jobs:

  - deployment: deploy_dev

    pool:
      vmImage: ubuntu-latest

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: app
            displayName: artifact download app

          # - task: AzureRmWebAppDeployment@4
          #   inputs:
          #     ConnectionType: AzureRM
          #     azureSubscription: Pay-As-You-Go(0518cd5b-d389-4983-9496-cdcae31dcc60)
          #     appType: webApp
          #     WebAppName: 2002-ng-notes-client
          #     packageForLinux: $(Pipeline.Workspace)/app
          #   displayName: azure app service deploy

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'projtwo'
              appType: 'webApp'
              appName: 'projtwo'
              package: '$(System.DefaultWorkingDirectory)/**/*.zip'
              deploymentMethod: 'auto'